# Generated by Django 3.0.8 on 2020-07-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projec',
            new_name='Project',
        ),
    ]
